services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      TSC_WATCHFILE: UsePolling
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
    volumes:
      - .:/app               # live code
      - /app/node_modules    # keep container's node_modules
      - next_cache:/app/.next  # dev cache stored in a named volume
    command: npm run dev

volumes:
  next_cache:
