services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
      NEXT_TELEMETRY_DISABLED: "1"
      HOSTNAME: "0.0.0.0"
      PORT: "3000"

      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: "465"
      SMTP_SECURE: "true"
      SMTP_USER: "no-reply@acumenintelligence.com"
      SMTP_PASS: "vlgo mlcc mclu iutx"
      MAIL_FROM: "Acumen Intelligence <no-reply@acumenintelligence.com>"
      MAIL_TO: "sheedh@acumenintellgence.com"

    restart: unless-stopped
