services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-web
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      NODE_ENV: "production"
      NEXT_CACHE_DIR: "/tmp/next-cache"  # prod: writable cache
    tmpfs:
      - /tmp
    restart: unless-stopped
    command: node server.js
    networks:
      - acumen_net

networks:
  acumen_net:
    external: true
