services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps   # keep your existing build target if you had one
    container_name: next-web
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      TSC_WATCHFILE: UsePolling
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
    volumes:
      - .:/app
      - /app/node_modules
      - next_cache:/app/.next
    command: npm run dev

volumes:
  next_cache: